replicaCount: 2

image:
  repository: yussufzoulfakar/chatpipeline
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

configMapName: chat-app-config
