---
# tasks file for roles/mongodb_role
- name: Add MongoDB Yum repo
  copy:
    content: |
      [mongodb-org-7.0]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://pgp.mongodb.com/server-7.0.asc
    dest: /etc/yum.repos.d/mongodb-org-6.0.repo
    mode: '0644'

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Allow remote connections in mongod.conf
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp:'
    line: '  bindIp: 0.0.0.0'
    backrefs: yes

- name: Start MongoDB service
  systemd:
    name: mongod
    state: started
    enabled: yes
    daemon_reload: yes

# Remove old Docker versions
- name: Remove old Docker versions
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  ignore_errors: yes

# Install required packages
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

# Add Docker repo
- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

# Install Docker
- name: Install Docker Engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# Start and enable Docker service
- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

# Add prometheus group
- name: Add prometheus group
  group:
    name: prometheus
    system: yes

# Add prometheus user
- name: Add prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    system: yes
    group: prometheus

# Run MongoDB exporter container
- name: Run MongoDB exporter container
  docker_container:
    name: mongodb_exporter
    image: percona/mongodb_exporter:0.44
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "9216:9216"
    command: "--mongodb.uri=mongodb://127.0.0.1:17001"

