name: Building_Image

on:
  push:
    branches: ['main']
    paths:
      - app/**      

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3



      #build the image
      - name: build the image
        working-directory: app

        run: |
         docker build -t yussufzoulfakar/chatpipeline .
         echo "$dockerhub_token" | docker login -u yussufzoulfakar --password-stdin
         docker push yussufzoulfakar/chatpipeline

