name: Kubectl_Reapply

on:
  workflow_run:
    workflows: ["Building_Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      #install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      #install helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --name appcluster --region $AWS_REGION


      - name: Uninstall existing Helm release (if exists)
        run: |
          if helm status chat-app --namespace default > /dev/null 2>&1; then
            helm uninstall chat-app --namespace default
          else
            echo "No existing release to uninstall."
          fi


      #install Helm
      - name: install Helm
        run: |
         helm install chat-app ./mychart






